# PLACEHOLDER — do not use as-is.
#
# This file is normally auto-generated by `nixos-generate-config` and is
# specific to the exact machine it was run on (disk UUIDs, kernel modules
# detected at install time, CPU microcode, etc.). It intentionally is NOT
# portable between machines, which is why it's the one file in this repo
# that can't be fully authored ahead of time.
#
# To generate the real one on the HTPC itself:
#   sudo nixos-generate-config --show-hardware-config > hosts/htpc/hardware-configuration.nix
#
# Do this from a live NixOS installer (fresh install) or from the running
# system (reinstall-in-place). Paste the output over this file, then double
# check the boot.initrd.availableKernelModules and fileSystems entries match
# your actual disk layout before rebuilding.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # --- fill in from the real nixos-generate-config output ---
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE-ME";
    fsType = "ext4";
  };

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/REPLACE-ME";
  #   fsType = "vfat";
  # };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # swap to hardware.cpu.intel.updateMicrocode if this box is Intel
}
